baseurl = "https://cocky-hopper-a03889.netlify.com"
title = "Planet Decred"

theme = "planetdecred-theme"

languagecode = "en"
defaultcontentlanguage = "en"




[params]

    keywords = "developer,opensource"    
    footercontent = ""
    description = "Planet Decred Website"

    main = "Planet Decred"
    info = "a community ecosystem of builders for the Decred blockchain."
    about =  "A community managed open source project building infrastructure for the Decred blockchain."

    chatTitle = "Join To The Planet Decred Chat"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true
    since = 2019

    rtl = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

